/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xurui_hellojni_HelloWorld */

#ifndef _Included_com_xurui_hellojni_HelloWorld
#define _Included_com_xurui_hellojni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xurui_hellojni_HelloWorld_A
#define com_xurui_hellojni_HelloWorld_A 1L
/*
 * Class:     com_xurui_hellojni_HelloWorld
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xurui_hellojni_HelloWorld_sayHi
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_xurui_hellojni_HelloWorld_accessField
        (JNIEnv *, jobject);

extern "C"
JNIEXPORT void JNICALL
Java_com_xurui_hellojni_HelloWorld_accessMethod
        (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif