{
  "formatVersion": "1.1",
  "component": {
    "group": "HelloTransform",
    "module": "lib",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toast-1.1.0.jar",
          "url": "toast-1.1.0.jar",
          "size": 12566,
          "sha512": "fa2cfb3fad673fc507132e0b4e94b8190dd7681b5b62b53ec2df47fa609dcc2681e7f102dca62da2577a52eb6c2f301727b5f6011312e0fcafbf263dbdfe5e21",
          "sha256": "d8cbd7b0b77ca235fc7094982df39567af52edaa14f447779c735bdeb647690d",
          "sha1": "3f782c1ef3788a9967ec7bdfb8479f93b70ceef8",
          "md5": "f5cdbdc2ca98b65b150c05fb2d2a7538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.22.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "toast-1.1.0.jar",
          "url": "toast-1.1.0.jar",
          "size": 12566,
          "sha512": "fa2cfb3fad673fc507132e0b4e94b8190dd7681b5b62b53ec2df47fa609dcc2681e7f102dca62da2577a52eb6c2f301727b5f6011312e0fcafbf263dbdfe5e21",
          "sha256": "d8cbd7b0b77ca235fc7094982df39567af52edaa14f447779c735bdeb647690d",
          "sha1": "3f782c1ef3788a9967ec7bdfb8479f93b70ceef8",
          "md5": "f5cdbdc2ca98b65b150c05fb2d2a7538"
        }
      ]
    }
  ]
}
