{
  "formatVersion": "1.1",
  "component": {
    "group": "HelloTransform",
    "module": "lib",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toast-1.3.0.jar",
          "url": "toast-1.3.0.jar",
          "size": 12188,
          "sha512": "1e8eb6180b8becd2bdc0fc634fd70f36bb3e8e4b741e32a7b3a30b4509cec947a644f9c9f22e8fe90aa387911803b32dff978aaf2c6637036aeeddb871ddc7c1",
          "sha256": "e7bdeaa9e0bb1f03b79159ac400163fcf8f2d511ff500feb2f29af03678d67f0",
          "sha1": "8c390b758c5540496972f0723ccccad88ab3db4b",
          "md5": "409ec94ff3f8c67a2c9229ba30c427a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.22.0-GA"
          }
        }
      ],
      "files": [
        {
          "name": "toast-1.3.0.jar",
          "url": "toast-1.3.0.jar",
          "size": 12188,
          "sha512": "1e8eb6180b8becd2bdc0fc634fd70f36bb3e8e4b741e32a7b3a30b4509cec947a644f9c9f22e8fe90aa387911803b32dff978aaf2c6637036aeeddb871ddc7c1",
          "sha256": "e7bdeaa9e0bb1f03b79159ac400163fcf8f2d511ff500feb2f29af03678d67f0",
          "sha1": "8c390b758c5540496972f0723ccccad88ab3db4b",
          "md5": "409ec94ff3f8c67a2c9229ba30c427a0"
        }
      ]
    }
  ]
}
